/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ProjectFinalRouteImport } from './routes/project.final'
import { Route as ProjectGorreanaRouteImport } from './routes/project.gorreana'
import { Route as ProjectMindfullRouteImport } from './routes/project.mindfull'
import { Route as ProjectSocialRouteImport } from './routes/project.social'
import { Route as ProjectSsbRouteImport } from './routes/project.ssb'
import { Route as ProjectStationeryRouteImport } from './routes/project.stationery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectFinalRoute = ProjectFinalRouteImport.update({
  id: '/project/final',
  path: '/project/final',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGorreanaRoute = ProjectGorreanaRouteImport.update({
  id: '/project/gorreana',
  path: '/project/gorreana',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectMindfullRoute = ProjectMindfullRouteImport.update({
  id: '/project/mindfull',
  path: '/project/mindfull',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSocialRoute = ProjectSocialRouteImport.update({
  id: '/project/social',
  path: '/project/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSsbRoute = ProjectSsbRouteImport.update({
  id: '/project/ssb',
  path: '/project/ssb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectStationeryRoute = ProjectStationeryRouteImport.update({
  id: '/project/stationery',
  path: '/project/stationery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/work': typeof WorkRoute
  '/project/final': typeof ProjectFinalRoute
  '/project/gorreana': typeof ProjectGorreanaRoute
  '/project/mindfull': typeof ProjectMindfullRoute
  '/project/social': typeof ProjectSocialRoute
  '/project/ssb': typeof ProjectSsbRoute
  '/project/stationery': typeof ProjectStationeryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/work': typeof WorkRoute
  '/project/final': typeof ProjectFinalRoute
  '/project/gorreana': typeof ProjectGorreanaRoute
  '/project/mindfull': typeof ProjectMindfullRoute
  '/project/social': typeof ProjectSocialRoute
  '/project/ssb': typeof ProjectSsbRoute
  '/project/stationery': typeof ProjectStationeryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/work': typeof WorkRoute
  '/project/final': typeof ProjectFinalRoute
  '/project/gorreana': typeof ProjectGorreanaRoute
  '/project/mindfull': typeof ProjectMindfullRoute
  '/project/social': typeof ProjectSocialRoute
  '/project/ssb': typeof ProjectSsbRoute
  '/project/stationery': typeof ProjectStationeryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/work'
    | '/project/final'
    | '/project/gorreana'
    | '/project/mindfull'
    | '/project/social'
    | '/project/ssb'
    | '/project/stationery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/work'
    | '/project/final'
    | '/project/gorreana'
    | '/project/mindfull'
    | '/project/social'
    | '/project/ssb'
    | '/project/stationery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/work'
    | '/project/final'
    | '/project/gorreana'
    | '/project/mindfull'
    | '/project/social'
    | '/project/ssb'
    | '/project/stationery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WorkRoute: typeof WorkRoute
  ProjectFinalRoute: typeof ProjectFinalRoute
  ProjectGorreanaRoute: typeof ProjectGorreanaRoute
  ProjectMindfullRoute: typeof ProjectMindfullRoute
  ProjectSocialRoute: typeof ProjectSocialRoute
  ProjectSsbRoute: typeof ProjectSsbRoute
  ProjectStationeryRoute: typeof ProjectStationeryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/final': {
      id: '/project/final'
      path: '/project/final'
      fullPath: '/project/final'
      preLoaderRoute: typeof ProjectFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/gorreana': {
      id: '/project/gorreana'
      path: '/project/gorreana'
      fullPath: '/project/gorreana'
      preLoaderRoute: typeof ProjectGorreanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/mindfull': {
      id: '/project/mindfull'
      path: '/project/mindfull'
      fullPath: '/project/mindfull'
      preLoaderRoute: typeof ProjectMindfullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/social': {
      id: '/project/social'
      path: '/project/social'
      fullPath: '/project/social'
      preLoaderRoute: typeof ProjectSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/ssb': {
      id: '/project/ssb'
      path: '/project/ssb'
      fullPath: '/project/ssb'
      preLoaderRoute: typeof ProjectSsbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/stationery': {
      id: '/project/stationery'
      path: '/project/stationery'
      fullPath: '/project/stationery'
      preLoaderRoute: typeof ProjectStationeryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WorkRoute: WorkRoute,
  ProjectFinalRoute: ProjectFinalRoute,
  ProjectGorreanaRoute: ProjectGorreanaRoute,
  ProjectMindfullRoute: ProjectMindfullRoute,
  ProjectSocialRoute: ProjectSocialRoute,
  ProjectSsbRoute: ProjectSsbRoute,
  ProjectStationeryRoute: ProjectStationeryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
